name: deploy-poetry-project
on: [push]
jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Set Poetry config
        run: |
          pip install poetry
          poetry install

      - name: Test with pytest
        run: poetry run pytest --cov . -n 2